spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fp
    username: postgres
    password: A8083aG3107
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update